spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@dearlavioncluster.xnanadi.mongodb.net/core-service?retryWrites=true&w=majority&appName=DearLavionCluster
      auto-index-creation: true
      socket-timeout: 20000
      connect-timeout: 10000
  main:
    allow-circular-references: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  redis:
    host: dearlavion-redis
    port: 6379
    timeout: 5000ms

server:
  port: 8082
  address: 0.0.0.0

auth:
  server:
    url: http://dearlavion-authentication-service:8081

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html